# Generated by Django 4.2.2 on 2023-07-04 16:40

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=400)),
                ('location', models.CharField(max_length=1000)),
                ('hotel_image', models.ImageField(upload_to='images/hotels/hotel_detail')),
                ('total_room', models.IntegerField(default=100)),
                ('vip_room', models.IntegerField(default=50)),
                ('normal_room', models.IntegerField(default=50)),
                ('is_bar_exist', models.BooleanField(default=True)),
                ('is_swimming_pool_exist', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_review', models.TextField()),
                ('review_date', models.DateField(auto_now_add=True)),
                ('review_time', models.TimeField(auto_now_add=True)),
                ('review_update_date', models.DateField(auto_now=True)),
                ('review_update_time', models.TimeField(auto_now=True)),
                ('user', models.ForeignKey(default=django.contrib.auth.models.AnonymousUser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_image', models.ImageField(upload_to='images/hotels')),
                ('hotel_detail', models.TextField()),
                ('hotel_review', models.ManyToManyField(blank=True, null=True, to='app.userreviewmodel')),
                ('hotel_service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_service_detail', to='app.hotelservicemodel')),
            ],
        ),
    ]
