# Generated by Django 4.2.2 on 2023-07-04 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_hoteldetailmodel_remove_hotelmodel_hotel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelmodel',
            name='hotel_review',
        ),
        migrations.RemoveField(
            model_name='hotelmodel',
            name='hotel_service_detail',
        ),
        migrations.AddField(
            model_name='hoteldetailmodel',
            name='hotel_review',
            field=models.ManyToManyField(blank=True, to='app.userreviewmodel'),
        ),
        migrations.AddField(
            model_name='hoteldetailmodel',
            name='hotel_service_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_service_detail', to='app.hotelservicemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelmodel',
            name='title',
            field=models.CharField(default='atom', max_length=200),
            preserve_default=False,
        ),
    ]
