# Generated by Django 4.2.2 on 2023-07-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230705_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationRentalsDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Vacation Rentals', max_length=200)),
                ('image', models.ImageField(upload_to='images/vacation')),
                ('room_type', models.CharField(default='PrivateRoom', max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('number_of_bed_room', models.IntegerField(default=1)),
                ('number_of_bath_room', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VacationRentalsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Vacation Rentals', max_length=200)),
                ('vacation_rentals_detail', models.ManyToManyField(to='app.vacationrentalsdetailmodel')),
            ],
        ),
    ]
