# Generated by Django 4.2.2 on 2023-07-05 18:20

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_vacationrentalsdetailmodel_vacationrentalsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous User', max_length=100)),
                ('webiste_review', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vacationrentalsdetailmodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('image', models.ImageField(upload_to='image/about_us')),
                ('user', models.ForeignKey(default=django.contrib.auth.models.AnonymousUser, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('website_review_detail', models.ManyToManyField(blank=True, related_name='website_review_detail', to='app.websitereviewmodel')),
            ],
        ),
    ]
