# Generated by Django 4.2.2 on 2023-07-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_bookingmodel_bookingconformationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='payment_type',
            field=models.CharField(choices=[('CashInFront', 'Cash In Front'), ('Khalti', 'Khalti')], default='CashInFront', max_length=200),
        ),
    ]
